/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PlantDoctorRouteImport } from './routes/plant-doctor'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as ConsultRouteImport } from './routes/consult'
import { Route as CartRouteImport } from './routes/cart'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShopIndexRouteImport } from './routes/shop.index'
import { Route as ServicesIndexRouteImport } from './routes/services.index'
import { Route as ProfileIndexRouteImport } from './routes/profile.index'
import { Route as BookingsIndexRouteImport } from './routes/bookings.index'
import { Route as ShopProductIdRouteImport } from './routes/shop.$productId'
import { Route as ProfileSupportRouteImport } from './routes/profile.support'
import { Route as ProfileSettingsRouteImport } from './routes/profile.settings'
import { Route as ProfileMembershipRouteImport } from './routes/profile.membership'
import { Route as ProfileGreenPointsRouteImport } from './routes/profile.green-points'
import { Route as ProfileEditRouteImport } from './routes/profile.edit'
import { Route as ProfileActivityRouteImport } from './routes/profile.activity'
import { Route as BookingsIdRouteImport } from './routes/bookings.$id'
import { Route as ServicesSlugIndexRouteImport } from './routes/services.$slug.index'
import { Route as ServicesSlugBookRouteImport } from './routes/services.$slug.book'

const PlantDoctorRoute = PlantDoctorRouteImport.update({
  id: '/plant-doctor',
  path: '/plant-doctor',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsultRoute = ConsultRouteImport.update({
  id: '/consult',
  path: '/consult',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopIndexRoute = ShopIndexRouteImport.update({
  id: '/shop/',
  path: '/shop/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileIndexRoute = ProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingsIndexRoute = BookingsIndexRouteImport.update({
  id: '/bookings/',
  path: '/bookings/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopProductIdRoute = ShopProductIdRouteImport.update({
  id: '/shop/$productId',
  path: '/shop/$productId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileSupportRoute = ProfileSupportRouteImport.update({
  id: '/profile/support',
  path: '/profile/support',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileSettingsRoute = ProfileSettingsRouteImport.update({
  id: '/profile/settings',
  path: '/profile/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileMembershipRoute = ProfileMembershipRouteImport.update({
  id: '/profile/membership',
  path: '/profile/membership',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileGreenPointsRoute = ProfileGreenPointsRouteImport.update({
  id: '/profile/green-points',
  path: '/profile/green-points',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileEditRoute = ProfileEditRouteImport.update({
  id: '/profile/edit',
  path: '/profile/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileActivityRoute = ProfileActivityRouteImport.update({
  id: '/profile/activity',
  path: '/profile/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingsIdRoute = BookingsIdRouteImport.update({
  id: '/bookings/$id',
  path: '/bookings/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesSlugIndexRoute = ServicesSlugIndexRouteImport.update({
  id: '/services/$slug/',
  path: '/services/$slug/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesSlugBookRoute = ServicesSlugBookRouteImport.update({
  id: '/services/$slug/book',
  path: '/services/$slug/book',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/consult': typeof ConsultRoute
  '/orders': typeof OrdersRoute
  '/plant-doctor': typeof PlantDoctorRoute
  '/bookings/$id': typeof BookingsIdRoute
  '/profile/activity': typeof ProfileActivityRoute
  '/profile/edit': typeof ProfileEditRoute
  '/profile/green-points': typeof ProfileGreenPointsRoute
  '/profile/membership': typeof ProfileMembershipRoute
  '/profile/settings': typeof ProfileSettingsRoute
  '/profile/support': typeof ProfileSupportRoute
  '/shop/$productId': typeof ShopProductIdRoute
  '/bookings/': typeof BookingsIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/shop/': typeof ShopIndexRoute
  '/services/$slug/book': typeof ServicesSlugBookRoute
  '/services/$slug/': typeof ServicesSlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/consult': typeof ConsultRoute
  '/orders': typeof OrdersRoute
  '/plant-doctor': typeof PlantDoctorRoute
  '/bookings/$id': typeof BookingsIdRoute
  '/profile/activity': typeof ProfileActivityRoute
  '/profile/edit': typeof ProfileEditRoute
  '/profile/green-points': typeof ProfileGreenPointsRoute
  '/profile/membership': typeof ProfileMembershipRoute
  '/profile/settings': typeof ProfileSettingsRoute
  '/profile/support': typeof ProfileSupportRoute
  '/shop/$productId': typeof ShopProductIdRoute
  '/bookings': typeof BookingsIndexRoute
  '/profile': typeof ProfileIndexRoute
  '/services': typeof ServicesIndexRoute
  '/shop': typeof ShopIndexRoute
  '/services/$slug/book': typeof ServicesSlugBookRoute
  '/services/$slug': typeof ServicesSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/consult': typeof ConsultRoute
  '/orders': typeof OrdersRoute
  '/plant-doctor': typeof PlantDoctorRoute
  '/bookings/$id': typeof BookingsIdRoute
  '/profile/activity': typeof ProfileActivityRoute
  '/profile/edit': typeof ProfileEditRoute
  '/profile/green-points': typeof ProfileGreenPointsRoute
  '/profile/membership': typeof ProfileMembershipRoute
  '/profile/settings': typeof ProfileSettingsRoute
  '/profile/support': typeof ProfileSupportRoute
  '/shop/$productId': typeof ShopProductIdRoute
  '/bookings/': typeof BookingsIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/shop/': typeof ShopIndexRoute
  '/services/$slug/book': typeof ServicesSlugBookRoute
  '/services/$slug/': typeof ServicesSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cart'
    | '/consult'
    | '/orders'
    | '/plant-doctor'
    | '/bookings/$id'
    | '/profile/activity'
    | '/profile/edit'
    | '/profile/green-points'
    | '/profile/membership'
    | '/profile/settings'
    | '/profile/support'
    | '/shop/$productId'
    | '/bookings/'
    | '/profile/'
    | '/services/'
    | '/shop/'
    | '/services/$slug/book'
    | '/services/$slug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cart'
    | '/consult'
    | '/orders'
    | '/plant-doctor'
    | '/bookings/$id'
    | '/profile/activity'
    | '/profile/edit'
    | '/profile/green-points'
    | '/profile/membership'
    | '/profile/settings'
    | '/profile/support'
    | '/shop/$productId'
    | '/bookings'
    | '/profile'
    | '/services'
    | '/shop'
    | '/services/$slug/book'
    | '/services/$slug'
  id:
    | '__root__'
    | '/'
    | '/cart'
    | '/consult'
    | '/orders'
    | '/plant-doctor'
    | '/bookings/$id'
    | '/profile/activity'
    | '/profile/edit'
    | '/profile/green-points'
    | '/profile/membership'
    | '/profile/settings'
    | '/profile/support'
    | '/shop/$productId'
    | '/bookings/'
    | '/profile/'
    | '/services/'
    | '/shop/'
    | '/services/$slug/book'
    | '/services/$slug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CartRoute: typeof CartRoute
  ConsultRoute: typeof ConsultRoute
  OrdersRoute: typeof OrdersRoute
  PlantDoctorRoute: typeof PlantDoctorRoute
  BookingsIdRoute: typeof BookingsIdRoute
  ProfileActivityRoute: typeof ProfileActivityRoute
  ProfileEditRoute: typeof ProfileEditRoute
  ProfileGreenPointsRoute: typeof ProfileGreenPointsRoute
  ProfileMembershipRoute: typeof ProfileMembershipRoute
  ProfileSettingsRoute: typeof ProfileSettingsRoute
  ProfileSupportRoute: typeof ProfileSupportRoute
  ShopProductIdRoute: typeof ShopProductIdRoute
  BookingsIndexRoute: typeof BookingsIndexRoute
  ProfileIndexRoute: typeof ProfileIndexRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
  ShopIndexRoute: typeof ShopIndexRoute
  ServicesSlugBookRoute: typeof ServicesSlugBookRoute
  ServicesSlugIndexRoute: typeof ServicesSlugIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/plant-doctor': {
      id: '/plant-doctor'
      path: '/plant-doctor'
      fullPath: '/plant-doctor'
      preLoaderRoute: typeof PlantDoctorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consult': {
      id: '/consult'
      path: '/consult'
      fullPath: '/consult'
      preLoaderRoute: typeof ConsultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/': {
      id: '/shop/'
      path: '/shop'
      fullPath: '/shop/'
      preLoaderRoute: typeof ShopIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/services'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/': {
      id: '/profile/'
      path: '/profile'
      fullPath: '/profile/'
      preLoaderRoute: typeof ProfileIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookings/': {
      id: '/bookings/'
      path: '/bookings'
      fullPath: '/bookings/'
      preLoaderRoute: typeof BookingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/$productId': {
      id: '/shop/$productId'
      path: '/shop/$productId'
      fullPath: '/shop/$productId'
      preLoaderRoute: typeof ShopProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/support': {
      id: '/profile/support'
      path: '/profile/support'
      fullPath: '/profile/support'
      preLoaderRoute: typeof ProfileSupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/settings': {
      id: '/profile/settings'
      path: '/profile/settings'
      fullPath: '/profile/settings'
      preLoaderRoute: typeof ProfileSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/membership': {
      id: '/profile/membership'
      path: '/profile/membership'
      fullPath: '/profile/membership'
      preLoaderRoute: typeof ProfileMembershipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/green-points': {
      id: '/profile/green-points'
      path: '/profile/green-points'
      fullPath: '/profile/green-points'
      preLoaderRoute: typeof ProfileGreenPointsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/edit': {
      id: '/profile/edit'
      path: '/profile/edit'
      fullPath: '/profile/edit'
      preLoaderRoute: typeof ProfileEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/activity': {
      id: '/profile/activity'
      path: '/profile/activity'
      fullPath: '/profile/activity'
      preLoaderRoute: typeof ProfileActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookings/$id': {
      id: '/bookings/$id'
      path: '/bookings/$id'
      fullPath: '/bookings/$id'
      preLoaderRoute: typeof BookingsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/$slug/': {
      id: '/services/$slug/'
      path: '/services/$slug'
      fullPath: '/services/$slug/'
      preLoaderRoute: typeof ServicesSlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/$slug/book': {
      id: '/services/$slug/book'
      path: '/services/$slug/book'
      fullPath: '/services/$slug/book'
      preLoaderRoute: typeof ServicesSlugBookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CartRoute: CartRoute,
  ConsultRoute: ConsultRoute,
  OrdersRoute: OrdersRoute,
  PlantDoctorRoute: PlantDoctorRoute,
  BookingsIdRoute: BookingsIdRoute,
  ProfileActivityRoute: ProfileActivityRoute,
  ProfileEditRoute: ProfileEditRoute,
  ProfileGreenPointsRoute: ProfileGreenPointsRoute,
  ProfileMembershipRoute: ProfileMembershipRoute,
  ProfileSettingsRoute: ProfileSettingsRoute,
  ProfileSupportRoute: ProfileSupportRoute,
  ShopProductIdRoute: ShopProductIdRoute,
  BookingsIndexRoute: BookingsIndexRoute,
  ProfileIndexRoute: ProfileIndexRoute,
  ServicesIndexRoute: ServicesIndexRoute,
  ShopIndexRoute: ShopIndexRoute,
  ServicesSlugBookRoute: ServicesSlugBookRoute,
  ServicesSlugIndexRoute: ServicesSlugIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
